 const account =  [ { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        balances:
        { available: 100,
        current: 110,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null },
        mask: '0000',
        name: 'Plaid Checking',
        official_name: 'Plaid Gold Standard 0% Interest Checking',
        subtype: 'checking',
        type: 'depository' },
    { account_id: 'NDvDA7yk57uKgmJP8N4XH6MorejqEyCWGg6Pg',
        balances:
        { available: 200,
        current: 210,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null },
        mask: '1111',
        name: 'Plaid Saving',
        official_name: 'Plaid Silver Standard 0.1% Interest Saving',
        subtype: 'savings',
        type: 'depository' },
    { account_id: 'jnBnwJ6QlJu53JnDRVgLh3Mnd6rVZwf17BWrq',
        balances:
        { available: null,
        current: 1000,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null },
        mask: '2222',
        name: 'Plaid CD',
        official_name: 'Plaid Bronze Standard 0.2% Interest CD',
        subtype: 'cd',
        type: 'depository' },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        balances:
        { available: null,
        current: 410,
        iso_currency_code: 'USD',
        limit: 2000,
        unofficial_currency_code: null },
        mask: '3333',
        name: 'Plaid Credit Card',
        official_name: 'Plaid Diamond 12.5% APR Interest Credit Card',
        subtype: 'credit card',
        type: 'credit' },
    { account_id: '7D7D8aNzEauZNWn76GxVivwzVMlJm7tg5mJ7n',
        balances:
        { available: 43200,
        current: 43200,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null },
        mask: '4444',
        name: 'Plaid Money Market',
        official_name: 'Plaid Platinum Standard 1.85% Interest Money Market',
        subtype: 'money market',
        type: 'depository' } ]

        export default account