        const transaction =  [ { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Travel', 'Airlines and Aviation Services' ],
        category_id: '22001000',
        date: '2017-02-15',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'United Airlines',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '9EQEGdj3AdUWEpmo1jzVUwVegxpRnduRv5NyM',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 6.33,
        category: [ 'Travel', 'Car Service', 'Ride Share' ],
        category_id: '22006001',
        date: '2017-02-13',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Uber 072515 SF**POOL**',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '3A4AQGxlpGhmZWq46yoLsdlqxwJGVKiqjByRL',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-02-10',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Tectra Inc',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'ynLnAMRmeMugZMA3zx8PsQ3eAGVv7WSyalRnM',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 2078.5,
        category: [ 'Payment' ],
        category_id: '16000000',
        date: '2017-02-09',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'AUTOMATIC PAYMENT - THANK',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'mndnrgw1kguB53wkKQrdI5mXnkGzoVuLoWZpr',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-02-09',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'KFC',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'bWvW86odJ6CaM6JB7x5nUDeQAXld5VFVkdpKE',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Shops', 'Bicycles' ],
        category_id: '19007000',
        date: '2017-02-09',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Madison Bicycle Shop',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'nnanBM9LzMuxBV7zr35gfBe3NlPk6Di65nqVE',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'NDvDA7yk57uKgmJP8N4XH6MorejqEyCWGg6Pg',
        account_owner: null,
        amount: 25,
        category: [ 'Payment', 'Credit Card' ],
        category_id: '16001000',
        date: '2017-01-31',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'CREDIT CARD 3333 PAYMENT *//',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'gWKWvP6j5PCa1g64DpRvUE9NkvGjnbfg6wpqv',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 5.4,
        category: [ 'Travel', 'Car Service', 'Ride Share' ],
        category_id: '22006001',
        date: '2017-01-31',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Uber 063015 SF**POOL**',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'BbEbrDWe6DcKQ5byrlGpHwXm3Nb6EruwpQojl',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: '7D7D8aNzEauZNWn76GxVivwzVMlJm7tg5mJ7n',
        account_owner: null,
        amount: 5850,
        category: [ 'Transfer', 'Debit' ],
        category_id: '21006000',
        date: '2017-01-30',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'ACH Electronic CreditGUSTO PAY 123456',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: 'ACH',
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '1EdEP4BX14UdPnNXjBapH1mk7QAlWGi5kxd91',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'jnBnwJ6QlJu53JnDRVgLh3Mnd6rVZwf17BWrq',
        account_owner: null,
        amount: 1000,
        category: [ 'Transfer', 'Deposit' ],
        category_id: '21007000',
        date: '2017-01-30',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'CD DEPOSIT .INITIAL.',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'NDvDA7yk57uKgmJP8N4XH6MvNqkmpxFWGgJ8M',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 78.5,
        category: [ 'Recreation', 'Gyms and Fitness Centers' ],
        category_id: '17018000',
        date: '2017-01-29',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Touchstone Climbing',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'GDvDjy6L5yuNkjpQRorZFVMJjo3RAqi1pQgxn',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: -500,
        category: [ 'Travel', 'Airlines and Aviation Services' ],
        category_id: '22001000',
        date: '2017-01-29',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'United Airlines',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'zXpXna1yQaFno45xmRENIoPLxA9EjNIoyzbmr',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 12,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-01-28',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: '3322',
        zip: null },
        name: 'McDonald\'s',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'KDvDp4W854umnGoyAPx3sWaL3D6bkvIV9LXNZ',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 4.33,
        category: [ 'Food and Drink', 'Restaurants', 'Coffee Shop' ],
        category_id: '13005043',
        date: '2017-01-28',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Starbucks',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'rnknjgo8dgu1qM6dAlKrUqPpnEQ8zLTlAnRMw',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 89.4,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-01-27',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'SparkFun',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'qyPyNbogxbUyqz7x3Q9KsqVDZ1Ed6yTdjZKMj',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'NDvDA7yk57uKgmJP8N4XH6MorejqEyCWGg6Pg',
        account_owner: null,
        amount: -4.22,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-01-26',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'INTRST PYMNT',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'on4nxJopBJuoJM7BAVRlUJMmn8jv6rcRZze8J',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Travel', 'Airlines and Aviation Services' ],
        category_id: '22001000',
        date: '2017-01-16',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'United Airlines',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'AE8EqxW7RxU1g8M7Qqz6U4l3zeQ9WEt1pdNJ6',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 6.33,
        category: [ 'Travel', 'Car Service', 'Ride Share' ],
        category_id: '22006001',
        date: '2017-01-14',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Uber 072515 SF**POOL**',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'lnxnq9oMK9uy5NVKkzWJsrwPjV46MptZqk374',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-01-11',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Tectra Inc',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'WDvDKLA65LuGe3mAKr1RhDVva7KmGdFlbDzyP',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 2078.5,
        category: [ 'Payment' ],
        category_id: '16000000',
        date: '2017-01-10',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'AUTOMATIC PAYMENT - THANK',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'EDGDawWM5wuKZpMNwzqyHVmDd1a7WwiXB1ne4',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Food and Drink', 'Restaurants' ],
        category_id: '13005000',
        date: '2017-01-10',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'KFC',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '8EeEWDPBkDURQa5GymW4UlkPD9bZneuwXGopw',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'eWlWbPDN5PCybKDd719zsjGvQPg47KuLbz9ok',
        account_owner: null,
        amount: 500,
        category: [ 'Shops', 'Bicycles' ],
        category_id: '19007000',
        date: '2017-01-10',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Madison Bicycle Shop',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'gWKWvP6j5PCa1g64DpRvUE9NkvGjnbfg6wpRl',
        transaction_type: 'place',
        unofficial_currency_code: null },
    { account_id: 'NDvDA7yk57uKgmJP8N4XH6MorejqEyCWGg6Pg',
        account_owner: null,
        amount: 25,
        category: [ 'Payment', 'Credit Card' ],
        category_id: '16001000',
        date: '2017-01-01',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'CREDIT CARD 3333 PAYMENT *//',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'pnNnaPmo3Pue9Nm3BQPqS9rRNlyvVzULvWM3y',
        transaction_type: 'special',
        unofficial_currency_code: null },
    { account_id: 'PDvDmQAn5QuJr8mMLNPzUVBbz1k9RNu7e96pr',
        account_owner: null,
        amount: 5.4,
        category: [ 'Travel', 'Car Service', 'Ride Share' ],
        category_id: '22006001',
        date: '2017-01-01',
        iso_currency_code: 'USD',
        location:
        { address: null,
        city: null,
        lat: null,
        lon: null,
        state: null,
        store_number: null,
        zip: null },
        name: 'Uber 063015 SF**POOL**',
        payment_meta:
        { by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'kW3WJxoZqxCRb7oqlrXJUbwWzl9KExCWjX5pB',
        transaction_type: 'special',
        unofficial_currency_code: null } ]

        export default transaction